Отрисовывает статистику игроков
htmlacademy-javascript/1084415-code-and-magick-21 pull request #2
Opened 2020-09-26 19:18 UTC by oderzhanie

2020-09-26 19:21 UTC, oderzhanie commented
@ElseeCCD У меня в линтере настройка no-var и он ругается на файл game.js. На что именно ругается Тревис не знаю, может на index?

2020-09-29 11:55 UTC, ElseeCCD requested changes

2020-09-29 11:55 UTC, ElseeCCD commented on js/stat.js
> +    const gridY = CLOUD_HEIGHT - (BAR_HEIGHT * times[i] / maxTime) - 25;
Думаю, стоит вынести в константу 25, чтобы было понятно, что это такое

2020-09-29 11:55 UTC, ElseeCCD commented on js/stat.js
> +    ctx.fillText(players[i], CLOUD_X + GAP + (GAP + BAR_WIDTH) * i, CLOUD_Y + 245);
то же самое, от магического числа 245 стоит избавиться )

2020-09-29 11:55 UTC, ElseeCCD commented on js/stat.js
> +    ctx.fillText(Math.round(times[i]), CLOUD_X + GAP + (GAP + BAR_WIDTH) * i, gridY - 20);
и тут от 20 тоже )

2020-09-30 18:16 UTC, ElseeCCD approved these changes

2020-09-30 18:16 UTC, merged